### ISSUE TITLE
[Bug]: setDataTable(viewTable) causes "setValue is a function" error

### ISSUE THREAD

**Issue by YL-09** [rakannimer/react-google-charts#805]
### Would you like to work on a fix?

- [ ] Check this if you would like to implement a PR, we are more than happy to help you go through the process.

### Current and expected behavior

When updating from version `4.0.1` to `4.0.2`, the method setDataTable(viewTable) causes an issue where the chart throws an error "setValue is not a function", the method `setValue` on the chartWrapper.getDataTable() object is missing. It was working in version 4.0.1 with setDataTable(dataTable). https://github.com/rakannimer/react-google-charts/commit/2d91574f6286ab88ac9f75a68ead5f8d90783af9#diff-434f94aad12e9fb6af07f08cc7e1b9a14c0bf0642f0ef026ad16ad949ff2e498R195

### Reproduction

Initialize a Google Chart using googleChartWrapper. Create a dataTable using google.visualization.arrayToDataTable. Create a viewTable using google.visualization.DataView. Pass the viewTable to googleChartWrapper.setDataTable as per the updated API. Attempt to manipulate the data using setValue or other methods.

### react-google-charts version

4.0.1
