### ISSUE TITLE
Typescript Support ?

### ISSUE THREAD

**Issue by GobbaFish** [rakannimer/react-google-charts#136]
Am using:
TypeScript v2.2.2
react v15.4.2

I cant find a react-google-charts.d.ts definition but couldnt find one. I attempted to create my own using https://github.com/Microsoft/dts-gen which got me a little further but now get an error 

"Build:JSX element class does not support attributes because it does not have a 'props' property"
 when I try using a Chart in my code

**Comment by Flavien** [comment]
I've been using this:

```
declare module "react-google-charts" {
    import * as React from "react";

    export class Chart extends React.Component<any, any> {

    }
}
```

**Comment by OracPrime** [comment]
`import { Chart } from "react-google-charts";
export class TimelineChart extends React.Component<ITimelineChartProps, void> {
    public render(): JSX.Element {
            return <Chart chartType="Timeline"
                data={this.props.data}
                options={this.props.chartOptions}
                graph_id={this.props.chartId}
                width="100%"
                height="800px"
                legend_toggle
                chartPackages={["corechart", "timeline"]} />;
    }
}`

Just works for me; Typescript 2.2.

**Comment by RakanNimer** [comment]
Would anyone be interested in doing a PR to support typescript out of the box ?

**Comment by kornicameister** [comment]
I've recently added `d.ts` to my project, it is kind of a different approach because I am reusing the `@types/google.visualization`. Due to limited usage, for now, it is hard for me to say that this is working well enough. Anyway here's reference, if you like this I might try and add typings directly here or `@types`.

Ref: https://github.com/kornicameister/korni/blob/60f1edfed793db7e30c21b4c9b4a2145b3683db6/src/types/index.d.ts

**Comment by rakannimer** [comment]
2.0.9+ ships with typescript declarations !

Try it out :)

**Comment by Fakkio** [comment]
@rakannimer with 2.0.9 a get this error:
`Module '"D:/path/to/my/project/node_modules/@types/react/index"' has no default export.`
🤔

**Comment by rakannimer** [comment]
Hmm, probably because the types rely on @types/react. (Will fix this in next release)

Meanwhie, can you try to add them as a dev dependency : `npm i -D @types/react` and see if it's resolved ?

**Comment by Fakkio** [comment]
I've already installed @types/react@16.4.7.
I think the error happen when you import react:
```import React from "react";```
but in typescript you usually import it using:
```import * as React from "react";```
because react for TS doesn't have a default export.

**Comment by rakannimer** [comment]
Can you try with `2.0.15` ?

**Comment by Fakkio** [comment]
I get this error with 2.0.15:
```
D:/path/to/my/project/node_modules/react-google-charts/dist/ReactGoogleCharts.d.ts
(69,11):
Cannot find module '../../../../../../../../../../Users/rn/Code/et3arraf-deployed/et3-mono-repo-2/farah/tensorflowjs-playground/src/react-google-charts/src/types'.
```

**Comment by rakannimer** [comment]
Ok, looks like it was again a type generation error. 
Can you try : `2.0.16` 😄

**Comment by Fakkio** [comment]
Now i get this, but this time maybe my fault:

```
(53,11): Types of property 'options' are incompatible.
  Type '{ chartArea: { bottom: number; left: number; right: number; top: number; }; legend: { position: s...' is not assignable to type 'Partial<Partial<{ width: number; height: number; is3D: boolean; title: string; backgroundColor: s...'.
    Object literal may only specify known properties, and 'chartArea' does not exist in type 'Partial<Partial<{ width: number; height: number; is3D: boolean; title: string; backgroundColor: s...'.
```

It seems he doesn't like `chartArea` option.

**Comment by rakannimer** [comment]
Thanks for the link ! 

I'm not sure I want to take on the maintenance burden of a complete Google Charts types definition, especially since it's available. 

I relaxed the type definitions for Google Chart Options to fix false negative errors. 

Your code should work on `2.0.17`

**Comment by Fakkio** [comment]
I know you must hate me right now, but i get another error on legend type definition:
```
(52,9): Types of property 'options' are incompatible.
  Type '{ chartArea: { bottom: number; left: number; right: number; top: number; }; legend: { position: s...' is not assignable to type 'Partial<Partial<{ [otherOptionKey: string]: any; width: number; height: number; is3D: boolean; ti...'.
    Type '{ chartArea: { bottom: number; left: number; right: number; top: number; }; legend: { position: s...' is not assignable to type 'Partial<Partial<{ [otherOptionKey: string]: any; width: number; height: number; is3D: boolean; ti...'.
      Types of property 'legend' are incompatible.
        Type '{ position: string; }' is not assignable to type 'string | undefined'.
          Type '{ position: string; }' is not assignable to type 'string'.
```

**Comment by rakannimer** [comment]
> I know you must hate me right now

Hehehe, not at all ! You're helping me find annoying issues, keep'em coming ! 😄 

(You can try : `2.0.18`)

**Comment by Fakkio** [comment]
you're too fast, I've just create a PR to help but 2.0.18 is fully working! TY!

**Comment by rakannimer** [comment]
Thanks for that 😄 !

Happy it worked :)

Cheers !

**Comment by rakannimer** [comment]
Closing this. Anyone reading this that has a types issues please open a separate issue !
